require File.dirname(__FILE__) + '/spec_helper'
require 'cukehead/freemind_writer'

module Cukehead

  describe "FreemindWriter" do

    it "should add newlines after tags because that's what FreeMind does" do
      writer = FreemindWriter.new
      x = writer.add_newline_after_tags("<fake TEXT='XML'><node TEXT='fake'/></fake>")
      x.should match "<fake TEXT='XML'>\n<node TEXT='fake'/>\n</fake>\n"
    end

    it "should take XML generated by FreemindBuilder and write it to a file" do
      builder = FreemindBuilder.new
      writer = FreemindWriter.new
      filename = File.join($testing_tmp, 'test.mm')
      File.delete(filename) if File.exist? filename
      writer.write_mm(filename, builder.xml)
      File.exist?(filename).should be_true
    end

  end

end
